#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Aliases
## git
alias git="hub"
alias g="git"
alias gst="git status"
alias gco="git checkout"
alias gc="git commit"
alias ga="git add"
alias gpu="git pull"
alias gp="git push"

## tmux
alias tatt="tmux attach"
alias tls="tmux ls"
alias mx="tmux new-session -As `basename $PWD`"

## misc
alias ...="cd ../.."
alias t="$HOME/bin/t.py --task-dir $HOME/tasks --list TODO --delete-if-empty"
alias tm="$HOME/bin/t.py --task-dir $HOME/tasks --list MOVIES --delete-if-empty"

