#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Completion
autoload -U +X bashcompinit && bashcompinit
## stack
eval "$(stack --bash-completion-script "$(which stack)")"

# Aliases
## git
alias git="hub"
alias g="git"
alias ga="git add"
alias gc="git commit"
alias gco="git checkout"
alias gst="git status"
alias gp="git push"
alias gpu="git pull"
unalias gs

## tmux
alias tatt="tmux attach"
alias tls="tmux ls"
alias mx="tmux new-session -As `basename $PWD`"

## misc
alias ...="cd ../.."
alias t="$HOME/bin/t.py --task-dir $HOME/tasks --list TODO --delete-if-empty"
alias tm="$HOME/bin/t.py --task-dir $HOME/tasks --list MOVIES --delete-if-empty"
alias yb="youtube-dl"
alias m="make"

# Variables
## PATH
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.stack/programs/x86_64-linux/ghc-7.8.4/bin:$PATH"

## EDITOR
export EDITOR="vim"

